language: csharp
solution: SunCalc-Net.sln
dotnet: 2.1.4
os:  
  - linux
  - osx
branches:  
  only:
    - master
script:
 - dotnet test ./SunCalc.Tests/SunCalc.Tests.csproj -c Release -f netcoreapp2.0
 - dotnet build -c Release
 - dotnet pack -c Release --no-build