language: csharp
solution: SunCalcNet.sln
dotnet: 2.2.202
mono: none
dist: xenial
install:
  - export FrameworkPathOverride=$(dirname $(which mono))/../lib/mono/4.6.1-api
branches:  
  only:
    - master
script:
 - dotnet --info
 - dotnet build -c Release SunCalcNet
 - dotnet test -c Release SunCalcNet.Tests
 - dotnet pack -c Release --no-build 