language: csharp
solution: SunCalcNet.sln
dotnet: 2.1.4
os:  
  - linux
  - osx
branches:  
  only:
    - master
script:
 - dotnet test ./SunCalcNet.Tests/SunCalcNet.Tests.csproj -c Release -f netcoreapp2.0
 - dotnet build -c Release -f netcoreapp2.0
 - dotnet pack -c Release /p:TargetFrameworks=netcoreapp2.0 --no-build 