version: '{build}'  
pull_requests:  
  do_not_increment_build_number: true
image: Visual Studio 2017
branches:  
  only:
  - master
nuget:  
  disable_publish_on_pr: true
build_script:  
- ps: .\build.ps1
test: off  
artifacts:  
- path: .\SunCalc\artifacts\**\*.nupkg
  name: NuGet
deploy:  
- provider: NuGet
  server: https://www.myget.org/F/kostebudinoski-ci/api/v3/index.json
  api_key:
    secure: +nQ5sXVNk9VkDE9rTlZp+l0tClZXrq8eGt4jaaj4dUJA9v2K7ZHKJT4v5VZZjlsN
  skip_symbols: true
  on:
    branch: master
- provider: NuGet
  name: production
  api_key:
    secure: Qh73/DEtMeZBCTdu350ZW8K/TY1qad0COeOQVoaN3Mkm3QLleRTn0MFAddq6sRTV
  on:
    branch: master
    appveyor_repo_tag: true